# FILE: src/forensiq/features/entropy.py
"""Shannon entropy computation for process names and paths.

Shannon entropy quantifies the randomness of a string. Legitimate Windows
process names have predictable, low entropy. Random strings generated by
malware droppers or packers have high entropy.

Reference: Shannon, C.E. (1948). "A Mathematical Theory of Communication".
"""

from __future__ import annotations

import math
from collections import Counter
from pathlib import Path


def _shannon_entropy(text: str) -> float:
    """Compute Shannon entropy (bits per character) of a string.

    H(X) = -Σ p(x) * log2(p(x))

    Args:
        text: Input string to compute entropy for.

    Returns:
        Float in [0.0, log2(len(charset))] ≈ [0.0, 8.0] for ASCII.
        Returns 0.0 for empty strings.
    """
    if not text:
        return 0.0

    freq = Counter(text)
    total = len(text)
    entropy = 0.0
    for count in freq.values():
        p = count / total
        entropy -= p * math.log2(p)

    return round(entropy, 6)


def compute_name_entropy(process_name: str) -> float:
    """Compute Shannon entropy of a process image name.

    The name is normalized before entropy computation:
        - Lowercased (case-insensitive comparison)
        - Extension stripped (e.g., 'svchost.exe' → 'svchost')
        - Null bytes removed

    Examples:
        compute_name_entropy("svchost.exe")    → ~2.75 bits (low)
        compute_name_entropy("xqkR9mBz.exe")  → ~3.5+ bits (high, suspicious)
        compute_name_entropy("a.exe")          → 0.0 bits (single char)

    Args:
        process_name: Raw process name string (may include extension).

    Returns:
        Shannon entropy in bits [0.0, 8.0].
    """
    if not process_name:
        return 0.0

    # Normalize: strip null bytes, lowercase, remove extension
    name = process_name.strip().rstrip("\x00").lower()
    name_stem = Path(name).stem

    # If stem is empty (e.g., ".dll" as a name), use the full name
    name_for_entropy = name_stem if name_stem else name

    return _shannon_entropy(name_for_entropy)


def compute_path_entropy(image_file_name: str) -> float:
    """Compute Shannon entropy of a process's full executable path.

    The full path is used (including directory components) since malware
    often drops payloads in temp directories with random names.

    Args:
        image_file_name: Full Windows path to the process executable.

    Returns:
        Shannon entropy in bits [0.0, 8.0]. Returns 0.0 for empty paths.
    """
    if not image_file_name:
        return 0.0

    path = image_file_name.strip().rstrip("\x00").lower()
    return _shannon_entropy(path)


def compute_path_depth(image_file_name: str) -> int:
    """Count the number of directory components in a Windows path.

    Normalizes both forward and backward slashes.

    Examples:
        compute_path_depth(r"C:\\Windows\\System32\\svchost.exe") → 3
        compute_path_depth(r"C:\\svchost.exe")                    → 1
        compute_path_depth("")                                      → 0

    Args:
        image_file_name: Windows path string.

    Returns:
        Number of path components (integer ≥ 0).
    """
    if not image_file_name:
        return 0

    path = image_file_name.strip().rstrip("\x00")
    # Normalize slashes and split
    path = path.replace("\\", "/")

    # Remove drive letter if present (e.g., "C:/")
    if len(path) >= 2 and path[1] == ":":
        path = path[2:]

    parts = [p for p in path.split("/") if p]
    # The last component is the filename, the rest are directories
    return len(parts)
