# FILE: src/forensiq/models/report.py
"""Pydantic v2 models for the ForensIQ analysis report.

Models:
    ThreatEvent         — Discrete threat detection event with MITRE ATT&CK mapping
    YARAResult          — A generated + validated YARA rule for an IOC
    DumpMetadata        — Memory dump provenance and analysis runtime info
    ForensiqReport      — The complete analysis report (passed to HTML renderer)
"""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path
from typing import Literal

from pydantic import BaseModel, Field, computed_field, field_validator

from forensiq.models.features import ProcessFeatureVector

# ─── Severity Level ───────────────────────────────────────────────────────────
SeverityLevel = Literal["critical", "high", "medium", "low"]


class ThreatEvent(BaseModel):
    """A discrete threat detection event correlated to a process and MITRE technique.

    ThreatEvents are generated by detection heuristics in the feature engineering
    and classification stages. They form the forensic timeline in the report.

    MITRE ATT&CK techniques covered:
        T1055       — Process Injection (generic)
        T1055.012   — Process Hollowing
        T1059.001   — PowerShell command execution
        T1036.005   — Masquerading (match legitimate name)
        T1003.001   — LSASS Memory (credential dumping)
        T1197       — BITS Jobs (persistence)
        T1140       — Deobfuscate/Decode Files or Information
        T1547.001   — Registry Run Keys / Startup Folder
        T1071       — Application Layer Protocol (C2)
        T1082       — System Information Discovery
    """

    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(tz=UTC),
        description="UTC timestamp when this event was detected (analysis time, not runtime).",
    )
    pid: int = Field(..., description="Process ID associated with this threat event", ge=0)
    process_name: str = Field(..., description="Name of the suspicious process")
    event_type: str = Field(
        ...,
        description="Short detection type identifier (e.g., 'malfind_pe_header', 'rwx_injection').",
    )
    severity: SeverityLevel = Field(
        ...,
        description="Threat severity: 'critical', 'high', 'medium', or 'low'.",
    )
    description: str = Field(
        ...,
        description="Human-readable description of what was detected and why it is suspicious.",
    )
    mitre_technique: str = Field(
        default="",
        description="MITRE ATT&CK technique ID (e.g., 'T1055.012'). Empty if not applicable.",
    )
    mitre_technique_name: str = Field(
        default="",
        description="Human-readable MITRE technique name (e.g., 'Process Hollowing').",
    )

    def __repr__(self) -> str:
        return f"ThreatEvent(pid={self.pid}, type={self.event_type!r}, severity={self.severity!r})"


class YARAResult(BaseModel):
    """A YARA rule generated by the Ollama LLM and validated by yara-python.

    YARA rules are generated for the top-N most suspicious processes,
    using their IOCs (memory addresses, DLL names, command line fragments) as hints.
    All rules are compiled with yara-python before inclusion in the report.
    Invalid rules are marked is_valid=False and never exported.
    """

    rule_name: str = Field(
        ...,
        description="Unique YARA rule identifier (ASCII, no spaces). "
        "Format: forensiq_<sanitized_process_name>_<pid>",
    )
    process_name: str = Field(..., description="Name of the process this rule targets")
    pid: int = Field(..., description="PID of the process this rule was generated for", ge=0)
    rule_text: str = Field(
        ...,
        description="Full YARA rule text. Only populated for valid rules.",
    )
    is_valid: bool = Field(
        default=False,
        description="True if yara-python successfully compiled this rule.",
    )
    validation_error: str = Field(
        default="",
        description="Error message from yara-python compilation. Empty string if is_valid=True.",
    )
    iocs_used: list[str] = Field(
        default_factory=list,
        description="List of IOC strings provided to the LLM as rule hints.",
    )
    generated_at: datetime = Field(
        default_factory=lambda: datetime.now(tz=UTC),
        description="UTC timestamp when this rule was generated.",
    )

    def __repr__(self) -> str:
        return f"YARAResult(rule_name={self.rule_name!r}, pid={self.pid}, is_valid={self.is_valid})"


class DumpMetadata(BaseModel):
    """Provenance and technical metadata for the analyzed memory dump.

    All paths stored as strings (not Path objects) for JSON serialization.
    SHA-256 of the dump file is computed during analysis for integrity verification.
    """

    dump_path: str = Field(..., description="Absolute path to the analyzed memory dump file")
    dump_sha256: str = Field(
        default="",
        description="SHA-256 hex digest of the dump file for integrity verification.",
    )
    dump_size_bytes: int = Field(
        default=0,
        description="Size of the memory dump file in bytes",
        ge=0,
    )
    analysis_start: datetime = Field(
        default_factory=lambda: datetime.now(tz=UTC),
        description="UTC timestamp when the analysis started.",
    )
    analysis_end: datetime | None = Field(
        None,
        description="UTC timestamp when the analysis completed. None if still in progress.",
    )
    volatility_version: str = Field(
        default="",
        description="Volatility 3 version string (from 'vol --version').",
    )
    forensiq_version: str = Field(
        default="",
        description="ForensIQ version string (from forensiq.__version__).",
    )
    os_profile: str = Field(
        default="",
        description="Detected OS profile/banner from the memory dump "
        "(e.g., 'Windows 10 Version 1903 (OS Build 18362)...').",
    )

    @field_validator("os_profile", mode="before")
    @classmethod
    def coerce_os_profile(cls, v: object) -> str:
        """Accept None and coerce to empty string."""
        return v if isinstance(v, str) else ""

    @property
    def dump_size_mb(self) -> float:
        """Return dump size in megabytes (2 decimal places)."""
        return round(self.dump_size_bytes / (1024 * 1024), 2)

    @computed_field  # type: ignore[prop-decorator]
    @property
    def analysis_duration_seconds(self) -> float | None:
        """Return analysis duration in seconds, or None if still running."""
        if self.analysis_end is None:
            return None
        delta = self.analysis_end - self.analysis_start
        return round(delta.total_seconds(), 2)

    @computed_field  # type: ignore[prop-decorator]
    @property
    def dump_filename(self) -> str:
        """Return just the filename of the dump (without directory)."""
        return Path(self.dump_path).name

    def __repr__(self) -> str:
        return (
            f"DumpMetadata("
            f"dump={self.dump_filename!r}, "
            f"size={self.dump_size_mb}MB, "
            f"os={self.os_profile!r})"
        )


class ForensiqReport(BaseModel):
    """The complete ForensIQ analysis report for a single memory dump.

    This is the top-level data model passed to the Jinja2 HTML report template.
    All fields required by the template are present here.
    """

    # ─── Dump provenance ──────────────────────────────────────────────────────
    metadata: DumpMetadata = Field(
        ...,
        description="Dump provenance and analysis runtime information.",
    )

    # ─── Analysis summary ─────────────────────────────────────────────────────
    total_processes: int = Field(
        default=0,
        description="Total number of processes found in the dump",
        ge=0,
    )
    suspicious_count: int = Field(
        default=0,
        description="Number of processes above the anomaly threshold (but below classification threshold)",
        ge=0,
    )
    malicious_count: int = Field(
        default=0,
        description="Number of processes classified as malicious by the XGBoost model",
        ge=0,
    )

    # ─── Forensic timeline ────────────────────────────────────────────────────
    timeline: list[ThreatEvent] = Field(
        default_factory=list,
        description="Chronological list of threat detection events found in the dump.",
    )

    # ─── Ranked process results ───────────────────────────────────────────────
    # All analyzed processes sorted by threat_score descending.
    # Used to generate the "Top suspicious processes" table in the HTML report.
    ranked_processes: list[ProcessFeatureVector] = Field(
        default_factory=list,
        description="All analyzed processes ranked by threat_score (highest first).",
    )

    # ─── YARA rules ───────────────────────────────────────────────────────────
    yara_results: list[YARAResult] = Field(
        default_factory=list,
        description="Generated YARA rules for suspicious processes. Only valid rules are listed.",
    )

    # ─── DLL / Malfind YARA scan hits ─────────────────────────────────────────
    # Results from scanning injected memory regions with built-in YARA rules.
    # Each item is a dict serialized from YARADLLHit.
    dll_yara_hits: list[dict] = Field(
        default_factory=list,
        description="Built-in YARA rule matches found in injected/malfind memory regions.",
    )

    # ─── ML model metadata ────────────────────────────────────────────────────
    model_info: dict[str, str] = Field(
        default_factory=dict,
        description="Model metadata: version, training date, dataset, accuracy metrics.",
    )

    # ─── LLM metadata ─────────────────────────────────────────────────────────
    # Records which local Ollama model produced the AI-generated content, or
    # that no local AI was available and a rule-based summary was used instead.
    # Keys: model (resolved tag or ""), status (ok|unavailable),
    #       requested_model (configured model name).
    llm_info: dict[str, str] = Field(
        default_factory=dict,
        description="Ollama model resolution info: resolved model, status, requested model.",
    )

    # ─── Detector plugin findings ─────────────────────────────────────────────
    # Results from all DetectorPlugin runs (cross-view, PE analysis, etc.)
    # Stored as plain dicts for JSON serialization compatibility.
    detector_findings: list[dict] = Field(
        default_factory=list,
        description="Findings from the DetectorRegistry plugin system.",
    )

    # ─── MITRE ATT&CK coverage ────────────────────────────────────────────────
    mitre_techniques: list[dict] = Field(
        default_factory=list,
        description="Deduplicated list of all MITRE ATT&CK techniques observed.",
    )

    # ─── Executive summary (Ollama-generated) ─────────────────────────────────
    executive_summary: str = Field(
        default="",
        description="Plain-language executive summary. Generated by the resolved local "
        "Ollama model, or a deterministic rule-based summary when no AI is available.",
    )

    # ─── Computed summary fields ──────────────────────────────────────────────

    @computed_field  # type: ignore[prop-decorator]
    @property
    def threat_level(self) -> SeverityLevel:
        """Overall threat level for the dump based on findings.

        Rules:
            critical → ≥3 malicious processes OR critical-severity ThreatEvents
            high     → ≥1 malicious process OR ≥2 high-severity events
            medium   → suspicious processes found but none classified malicious
            low      → no suspicious processes found
        """
        if not self.ranked_processes:
            return "low"

        critical_events = sum(1 for e in self.timeline if e.severity == "critical")
        if self.malicious_count >= 3 or (self.malicious_count >= 1 and critical_events >= 1):
            return "critical"
        if self.malicious_count >= 1:
            return "high"
        if self.suspicious_count >= 1:
            return "medium"
        return "low"

    @computed_field  # type: ignore[prop-decorator]
    @property
    def valid_yara_count(self) -> int:
        """Number of successfully validated YARA rules in the report."""
        return sum(1 for r in self.yara_results if r.is_valid)

    @computed_field  # type: ignore[prop-decorator]
    @property
    def top_threats(self) -> list[ProcessFeatureVector]:
        """Return the top 10 most suspicious processes (for report summary table)."""
        return [p for p in self.ranked_processes if p.is_malicious][:10]

    def __repr__(self) -> str:
        return (
            f"ForensiqReport("
            f"dump={self.metadata.dump_filename!r}, "
            f"processes={self.total_processes}, "
            f"malicious={self.malicious_count}, "
            f"threat_level={self.threat_level!r})"
        )
